Repository REUBATCODE/leify, pull requests merged in 2024-03, with the labels that each got.

#33 Vista de album
  composer.lock
  package-lock.json
  resources/views/album.blade.php
  routes/web.php
  tailwind.config.js
Labels: epic-guest

#37 auth de registro por emails en desarrollo
  app/Models/User.php
  database/migrations/2024_02_21_013510_update_users_table.php
Labels: epic-guest

#44 cargamos el usuario registrado modificamos las rutas segun el correct…
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
Labels: enhancement

#50 busca albums y renderiza albums en una vista
  app/Http/Controllers/AlbumController.php
  resources/views/albums/index.blade.php
  resources/views/albums/view.blade.php
  resources/views/components/header.blade.php
  routes/web.php
Labels: epic-albums

#53 Fix view individual usuario
  app/Http/Controllers/ProfileController.php
  app/Providers/AppServiceProvider.php
  resources/views/artists/view.blade.php
Labels: enhancement

#56 Fix vista individual
  app/Http/Controllers/ProfileController.php
  resources/views/artists/update.blade.php
  resources/views/artists/view.blade.php
  resources/views/components/header.blade.php
  resources/views/layouts/navigation.blade.php
  resources/views/profile/edit.blade.php
  resources/views/profile/partials/update-password-form.blade.php
  resources/views/profile/partials/update-profile-information-form.blade.php
  routes/web.php
Labels: bug
